### PR TITLE
Detect for a composer.json file aswell as index.php

### PR DESCRIPTION
**Pull request by henrikbjorn**
Detect for a composer.json file aswell as index.php allows to not create... empty index.php file for projects that are using Symfony, Silex and so on

Tested as `./bin/detect /path/to/symfony-app` and it returns `PHP (HHVM)` as expected.

This fixes GH #1

### CODE REVIEW

**Comment by ptarjan** [comment]
Thanks.

Are the routes working correctly for a Symfony app or do we need a `config.hdf` to rewrite some things?

**Comment by henrikbjorn** [comment]
A `config.hdf` is needed to route all request to a single `php` file with `qsa`, but that is easily done and that is okay to be in the root imo :)

**Comment by ptarjan** [comment]
Can you make an example? And if there is an easy way to detect which config to use when, can you we default to doing it correctly?

**Comment by henrikbjorn** [comment]
There is no easy way to detect this, as Silex, Laravel, eZ Publish, Drupal and more will adopt some or every Symfony component :)

https://github.com/E1379/symfony-standard/compare/symfony:f469a46722ce2cd2fd34427e8aaff0ffeaa1ae05...hhvm found this curtesy of http://labs.qandidate.com/blog/2013/10/21/running-symfony-standard-on-hhvm/

**Comment by ptarjan** [comment]
Ok, we'll leave it like this and see how people use it. Thanks for your help.

**Pull request merged**
